# This is a basic workflow to help you get started with Actions

name: Dependency Updates Slack Notifier

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependency_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Dependency Updates
        run: ./gradlew dependencyUpdates --refresh-dependencies

      - name: Post results on Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C03CPGWLNAX'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
