name: Dependency Updates Slack Notifier

on:
  schedule:
    # At 06:00 on every Saturday
    - cron: "0 6 * * */6"

  workflow_dispatch:

jobs:
  dependency_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Dependency Updates
        run: ./gradlew dependencyUpdates --refresh-dependencies

      - name: Read contents from dependency_update_report.txt
        id: dependency_report
        uses: juliangruber/read-file-action@v1
        with:
          path: ./build/dependencyUpdates/dependency_update_report.txt

      - name: Post results on Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C03CPGWLNAX'
          slack-message: "GitHub build result: ${{ job.status }}\n\n${{ steps.dependency_report.outputs.content }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
